nc: 91  # No. of classes
coco: True  # uses the default pre-trained head if true
train: coco/train2017  # dir path containing train images
train_annotation: coco/annotations/instances_train2017.json  # COCO train JSON file
val: coco/val2017  # dir path containing val images
val_annotation: coco/annotations/instances_val2017.json  # COCO validation JSON file
optimizer: SGD  # SGD | AdamW
momentum: 0.9
lr: !!float 4e-4
decay: !!float 4e-5  # weight decay
scaler: true  # performs mixed-precision training if true
batch: 8  # 4 is recommended for 12GB VRAM
workers: 6
epoch: 39
step_size: 9  # stepLR interval
gamma: 0.5  # stepLR multiplicator
# eval config
visualize: True  # saves the prediction results instead of computing scores
weight: weights/best.pth  # model weight
conf_thr: 0.5  # confidence score threshold
iou_thr: 0.5  # IoU score threshold
mask_thr: 0.7  # segmentation mask threshold